# Homework Assignment 2

You will be analyzing an xyz file for water (water.xyz) and measuring the distances between all the atoms in the molecule.  The file is located in the data folder of your workshop materials. The output of your code should look like this.

```
O to O : 0.0
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.0
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.0
```
To do this you will need to use the distance formula.

$$distance = \sqrt{(x_1 - x_2)^2 + (y_1 - y_2)^2 + (z_1 - z_2)^2}$$

As you can see that you will need to square stuff and take the square root.  To take the square root, you will use a function from numpy, `numpy.sqrt()`.  To square something, use `**` notation.  As in, `3**2 = 9` is $3^2 =9$.

In [1]:
import os
import numpy

In [42]:
file_location = os.path.join('data','water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)
print(file_location)

data/water.xyz


In [5]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [6]:
symbols = xyz_file[:,0]
coords = xyz_file[:,1:]
coords = coords.astype(numpy.float)

<ipython-input-6-0915b38f976b>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coords = coords.astype(numpy.float)


In [7]:
print(symbols)
print(coords)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [9]:
num_atoms = len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coords[num1,0] - coords[num2,0]
        y_distance = coords[num1,1] - coords[num2,1]
        z_distance = coords[num1,2] - coords[num2,2]
        distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


In [13]:
#Modify my code to only print atoms that are actually bonded
#Rule: Distance between atoms is less than 1.5 angstroms

In [17]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
            x_distance = coords[num1,0] - coords[num2,0]
            y_distance = coords[num1,1] - coords[num2,1]
            z_distance = coords[num1,2] - coords[num2,2]
            distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance > 0 and distance < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


## Writing and Using Functions

In [18]:
#def function_name(parameters):
#    ** body of your function **
#    ** write code using the parameters to calculate something **
#    return value_to_return

In [19]:
def calculate_distance(coords1,coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [20]:
calculate_distance([0,0,0],[0,0,1])

1.0

In [21]:
calculate_distance([0,0,0],[1,1,1])

1.7320508075688772

In [23]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
            distance = calculate_distance(coords[num1],coords[num2])
            
            if distance > 0 and distance < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [24]:
# Write a function to check and see if a distance is a bond
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance < 1.5:
        return True
    else:
        return False

In [25]:
bond_check(1.7)

False

In [26]:
bond_check(1.2)

True

In [27]:
bond_check(-50)

False

In [56]:
# Modify the bond check function to take a minimum and a maximum length as an input
def bond_check(atom_distance, min_length=0, max_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Defaults: minimum: 0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance > min_length and atom_distance < max_length:
        return True
    else:
        return False

In [57]:
bond_check(1.7, 0, 2)

True

In [38]:
bond_check(1.7)

False

In [39]:
bond_check(1.7, max_length=2)

True

In [40]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(atom_distance, min_length=0, max_length=1.5)
    Checks if a distance is a bond based on a minimum and maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Defaults: minimum: 0 angstroms, maximum: 1.5 angstroms



In [41]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
            distance = calculate_distance(coords[num1],coords[num2])
            
            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [43]:
# Write a new function called open_xyz that opens and processes an xyz file. Your function
# should accept a file path for the input.
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats.
    """
    xyz_file = numpy.genfromtxt(fname=filename, dtype='unicode', skip_header=2)
    symbols = xyz_file[:,0]
    coords = xyz_file[:,1:]
    coords = coords.astype(numpy.float)
    return symbols, coords

In [60]:
import os
import numpy

def calculate_distance(coords1,coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

def bond_check(atom_distance, min_length=0, max_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Defaults: minimum: 0 angstroms, maximum: 1.5 angstroms
    """
    if atom_distance > min_length and atom_distance < max_length:
        return True
    else:
        return False

def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings and the coordinates as floats.
    """
    xyz_file = numpy.genfromtxt(fname=filename, dtype='unicode', skip_header=2)
    symbols = xyz_file[:,0]
    coords = xyz_file[:,1:]
    coords = coords.astype(float)
    return symbols, coords

file_location = os.path.join('data','water.xyz')
symbols, coordinates = open_xyz(file_location)

#print(calculate_distance(coordinates[0],coordinates[1]))
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            distance=calculate_distance(coordinates[num1],coordinates[num2])
            if bond_check(distance) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969
